# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 The Foundation for Public Code <info@publiccode.net>

title: Foundation for Public Code repository link checks
version: 0.0.0

plugins:
  - jekyll-sitemap

remote_theme: publiccodenet/jekyll-theme
baseurl: /publiccodenet-url-check
