# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2021-2023 The Foundation for Public Code <info@publiccode.net>

name: Scheduled link check
on:
  workflow_dispatch: {}
  schedule:
#             ┌───────────── minute (0 - 59)
#             │ ┌───────────── hour (0 - 23)
#             │ │ ┌───────────── day of the month (1 - 31)
#             │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#             │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#             │ │ │ │ │
#             │ │ │ │ │
#             │ │ │ │ │
#             * * * * *
    - cron:  '9 2 * * *' # every day at 02:09 UTC

defaults:
  run:
    shell: bash

jobs:
  link-check:
    if: ${{ github.repository == 'publiccodenet/publiccodenet-url-check' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update-deps
        run: sudo apt-get update
      - name: upgrade-deps
        run: sudo apt-get upgrade -y
      - name: install-deps
        run: >
          sudo apt-get install -y
          make
          python3
      - run: make check
