# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2021-2023 The Foundation for Public Code <info@publiccode.net>

name: Scheduled link check
on:
  workflow_dispatch: {}
  schedule:
#             ┌───────────── minute (0 - 59)
#             │ ┌───────────── hour (0 - 23)
#             │ │ ┌───────────── day of the month (1 - 31)
#             │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#             │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#             │ │ │ │ │
#             │ │ │ │ │
#             │ │ │ │ │
#             * * * * *
    - cron:  '9 2 * * *' # every day at 02:09 UTC

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  link-check:
    if: ${{ github.repository == 'publiccodenet/publiccodenet-url-check' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: drop-some-bloat
        run: sudo apt-get remove -y firefox
      - name: update-deps
        run: sudo apt-get update
      - name: upgrade-deps
        run: sudo apt-get upgrade -y
      - name: install-deps
        run: >
          sudo apt-get install -y
          libxml2-utils
          make
          nodejs
          python3
          python3-docopt
          ruby
          ruby-bundler
          wget
      - name: bundle-install
        run: bundle install
      - name: fetch-previous-results
        run: wget https://publiccodenet.github.io/publiccodenet-url-check/url-check-results.json
      - name: build-site
        run: make build
      - name: report-built-files
        run: find _site -ls
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
      - name: report-failure-on-bad-urls
        run: URL_CHECK_JUST_RAN=1 make check
